### test app
GET http://localhost:4000/


### test all schemas
GET http://localhost:4000/schema/all

### test schema
GET http://localhost:4000/schema/test


### test schema
GET http://localhost:4000/schema/test/elements