### Test hello
GET http://localhost:6000/users/hello

### Test authenticate test:test encoded
POST http://localhost:6000/users/authenticate
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### Test getAll authenticated test:test base64 encoded
GET http://localhost:6000/users/
Authorization: Basic dGVzdDp0ZXN0

### Test verify authdata
GET http://localhost:6000/users/verify
Authorization: Basic dGVzdDp0ZXN0